apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  labels:
    app: webapp
spec:
  replicas: 3
  template:
    metadata:
      name: webapp-pod
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: nginx
  selector:
    matchLabels:
      app: webapp
    