apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: dev # namespace
  labels:
    name: myapp
    type: front-end
spec:
  containers:
    - name: myapp-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
